### ISSUE TITLE
Taal van je document

### ISSUE THREAD

**Issue by KrijnHoetmer** [Davidvboxt/the-client-case#1]
Is deze site echt in het Engels? :)

https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/page-1.html#L2

**Comment by Davidvboxt** [comment]
> Is deze site echt in het Engels? :)
> 
> https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/page-1.html#L2

Ik heb het veranderd naar nederlands :)
