### ISSUE TITLE
Heading structuur

### ISSUE THREAD

**Issue by KrijnHoetmer** [Davidvboxt/the-client-case#2]
Pas op met het overslaan van heading levels.

https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/index.html#L18-L19

**Comment by Davidvboxt** [comment]
> Pas op met het overslaan van heading levels.
> 
> https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/index.html#L18-L19

Ik heb de h4 veranderd naar een h2 voor een betere topografie
