### ISSUE TITLE
Duplicate ID's

### ISSUE THREAD

**Issue by KrijnHoetmer** [Davidvboxt/the-client-case#3]
ID's horen uniek te zijn, dus misschien doet dit dingen die je niet verwacht.

https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/index.html#L23-L24

**Comment by Davidvboxt** [comment]
> ID's horen uniek te zijn, dus misschien doet dit dingen die je niet verwacht.
> 
> https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/index.html#L23-L24

De ID's heb ik leeg gemaakt voor verwarring. Mocht ik er ooit gebruik van maken bedenk ik een toepasselijke id voor elke input
