### ISSUE TITLE
Content/link in iframe?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Davidvboxt/the-client-case#4]
Er staat een link in je iframe, is dit de bedoeling? (Valideer je document ook even om te kijken of dit überhaupt kan/mag.)

https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/index.html#L81-L84

**Comment by Davidvboxt** [comment]
De link heb ik verwijderd

> Er staat een link in je iframe, is dit de bedoeling? (Valideer je document ook even om te kijken of dit überhaupt kan/mag.)
> 
> https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/index.html#L81-L84

De link heb ik verwijderd omdat het inderdaad niet de bedoeling en nuttig was
