### ISSUE TITLE
Semantische HTML

### ISSUE THREAD

**Issue by KrijnHoetmer** [Davidvboxt/the-client-case#7]
Die `<strong>` hier lijkt op iets anders.. Wat zou hier een lekkerder element zijn?

https://github.com/Davidvboxt/the-client-case/blob/56f6571b00accebae19e27009c11576fa56cbd5d/page-1.html#L24-L26

**Comment by Davidvboxt** [comment]
<h2>OBA Oosterdok</h2>
        <b>Adress</b>
        <p>Oosterdokskade 143</p>
